Laravel/invoice_app/routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index');
Route::resource('invoices', 'InvoiceController');
Route::resource('lineitems', 'LineItemController');
Route::resource('customers', 'CustomerController');

Route::resource('/permissions', 'PermissionController');
Route::resource('/roles', 'RoleController');


Route::get('/modals', 'PageController@modalView');

Laravel/invoice_app/app/Http/Controllers/PermissionController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Spatie\Permission\Models\Role;
use Spatie\Permission\Models\Permission;

class PermissionController extends Controller
{

    public function __construct()
    {
        $this->middleware('auth'); // creates exception to the authentication
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $permissions = Permission::with('roles')->get();

        return view('permissions.index', compact('permissions'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $roles = Role::all();

        return view('permissions.create', compact('roles'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $permission = Permission::create(['name' => $request->permission]);

      /*   // //  now here we got the array of roles so assign permission to all roles in loop
        foreach ($request->roles as $value) {
            $role = Role::find($value); //Here $value is a roles id

             // so now here assign a role
             $permission->assignRole($role);
        } */
        $permission->syncRoles($request->roles);

        return redirect()->back();
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $permission = Permission::find($id);

        $roles = Role::all();

        return view('permissions.edit', compact('permission','roles'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $permission = Permission::find($id);
        $permission->name = $request->permission;
        $permission->save();

        if($request->remove_permission === 'on') {
            $permission->syncRoles([]);
        } else {
            $permission->syncRoles($request->roles);
        }

        return redirect()->back();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

Laravel/invoice_app/resources/views/permissions/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">
                    Permission
                </div>

                <div class="card-body">
                    <form action="{{ route('permissions.store') }}" method="post">
                        @csrf
                        <div class="form-group row">
                            <label for="permission" class="col-md-4 col-form-label text-md-right">
                                {{ __('Permission Name') }}
                            </label>

                            <div class="col-md-6">
                                <input id="permission" type="text" class="form-control @error('permission') is-invalid @enderror" name="permission" value="{{ old('permission') }}" required autofocus autocomplete="off">

                                @error('permission')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="parent" class="col-md-4 col-form-label text-md-right">
                                {{ __('Roles') }}
                            </label>

                            <div class="col-md-6">
                                <select
                                    multiple
                                    id="role"
                                    class="form-control @error('roles') is-invalid @enderror"
                                    name="roles[]"
                                    autofocus
                                >
                                    <option>None</option>
                                    @foreach ($roles as $role)
                                        <option value="{{ $role->id }}">
                                            {{ $role->name }}
                                        </option>
                                    @endforeach
                                </select>
                                @error('role')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>
                        <div class="form-group row mb-0">
                            <div class="col-md-6 offset-md-4">
                                <button type="submit" class="btn btn-primary">
                                    {{ __('Save Permission') }}
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

Laravel/invoice_app/resources/views/permissions/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">
                    Permission
                </div>

                <div class="card-body">
                    <form
                        action="{{ route('permissions.update', $permission->id) }}"
                        method="post"
                    >
                        @csrf
                        @method('put')
                        <div class="form-group row">
                            <label for="permission" class="col-md-4 col-form-label text-md-right">
                                {{ __('Permission Name') }}
                            </label>

                            <div class="col-md-6">
                                <input
                                    id="permission"
                                    type="text"
                                    class="form-control
                                    @error('permission') is-invalid @enderror"
                                    name="permission"
                                    value="{{ $permission->name }}"
                                    required
                                    autofocus
                                    autocomplete="off"
                                >

                                @error('permission')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="parent" class="col-md-4 col-form-label text-md-right">
                                {{ __('Roles') }}
                            </label>

                            <div class="col-md-6">
                                <select
                                    id="role"
                                    class="form-control
                                    @error('roles') is-invalid @enderror"
                                    name="roles[]"
                                    autofocus
                                    multiple
                                >
                                    @foreach ($roles as $role)
                                        <option
                                            value="{{ $role->id }}"
                                            @if(in_array($role->id, $permission->roles->pluck('id')->toArray()))
                                            selected
                                            @endif
                                        >
                                            {{ $role->name }}
                                        </option>
                                    @endforeach
                                </select>
                                @error('role')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>
                        <div class="form-group row">
                            <div class="form-check col-md-6 offset-md-4">
                                <input
                                    class="form-check-input"
                                    type="checkbox"
                                    name="remove_permission"
                                    id="remove_permission"
                                >
                                <label class="form-check-label" for="remove_permission">
                                    Remove Roles
                                </label>
                            </div>
                        </div>
                        <div class="form-group row mb-0">
                            <div class="col-md-6 offset-md-4">
                                <button type="submit" class="btn btn-primary">
                                    {{ __('Save Permission') }}
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

Laravel/invoice_app/resources/views/permissions/index.blade.php
@extends('layouts.app')

@section('styles')
<style>

</style>
@endsection

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">
                    <div class="float-left">
                        Permission
                    </div>
                    <div class="float-right">
                        <a class="btn btn-primary" href="{{ route('permissions.create') }}" >
                            {{ __('Create Permission') }}
                        </a>
                    </div>
                </div>
                <div class="card-body">
                    <table class="table">
                        <thead class=>
                            <tr>
                                <th>#</th>
                                <th>Name</th>
                                <th>Role</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach ($permissions as $key => $permission)
                            <tr>
                                <td>
                                    {{ $key + 1 }}
                                </td>
                                <td>
                                    {{ $permission->name }}
                                </td>
                                <td>
                                    @foreach ($permission->roles as $role)
                                        {{ $role->name }} |
                                    @endforeach
                                </td>
                                 <td>
                                    <a
                                        class="btn btn-primary"
                                        href="{{ route('permissions.edit', $permission->id)}}"
                                    >
                                        Edit
                                    </a>
                                </td>
                            </tr>
                            @endforeach
                        </tbody>
                    </table>

                </div>
            </div>
        </div>
    </div>
</div>
@endsection